### ISSUE TITLE
Baugruppen Import

### ISSUE THREAD

**Issue by asicnet** [Part-DB/Part-DB-legacy#33]
Habe versucht Bauteile in einer CSV Datei zu einer Baugruppe zu importieren.
Keine Chance, da es einen Fileimport nicht gibt und das Textfenster was eingeben und dann imprtieren geht auch nicht!
Entweder Fehlermeldung oder keine Fehlermeldung - aber auch kein Import oder sonst was.

Es geht nicht!!

Bis dann
H

**Comment by jbtronics** [comment]
> Es geht nicht!!

Da hast absolut recht. Weder die dargestellten Beispiele, die Beispiel-Dateien, oder die Exportausgaben der Baugruppen funktionieren mit dieser Import funktion...
Ich habe die Funktion jetzt mal ausgeblendet, weil ich das jetzt nicht so ohne weiteres nicht fixen kann und ein nichtfunktioniernder Dialog verwirrend ist.

Ich muss das komplette Import/Exportsystem komplett neuschreiben (der Code dürfte noch komplett aus den allerersten Versionen von Part-DB stammen und nicht mehr verbessert worden zu sein), denn ansonsten sehe ich keine sinnvolle möglichkeit, diese Funktion noch zu retten.

**Comment by ttoopp** [comment]
Hi, wenn ich mit der aktuellen Master Version versuche eine CSV zu importieren, passiert leider nichts :(

**Comment by mueschel** [comment]
Warte ebenfalls ungeduldig. Dieses Feature ist so ziemlich das einzige, weswegen ich an meiner uralten 0.3.1 hänge und nicht upgrade. Bei Baugruppen mit mehr als ein paar Dutzend Bauteilen geht es ohne Import leider nicht.
Ich hoffe es findet sich Zeit!

**Comment by jbtronics** [comment]
Should be possible with the Part-DB rewrite: https://github.com/Part-DB/Part-DB-server
