### ISSUE TITLE
Where can I see the number of devices produced?

### ISSUE THREAD

**Issue by emsit** [Part-DB/Part-DB-legacy#52]
Hello,
When I remove the parts from the store (Device, Multiplicator, Remove Stock (-)), where I can see that the devices are being manufactured (see their number in stock?).

Thanks.

**Comment by jbtronics** [comment]
What exactly do you mean? Do you want to see how many devices has has been taken from the instock (so when you Remove Stock via the devices dialog, these value gets incremented by the multiplicator?)

These informations are not really saved in the DB yet, so it is not possible to show this info.

But I can try to implement that feature (maybe in a big rewrite of the devices system, in the moment it has some flaws...)

**Comment by emsit** [comment]
I want to know how many components I have to take physically out of the warehouse when I have manufactured 5 devices, for example.
And it would be good to see in the warehouse that I got 5 pieces of devices.

For example, PartKeepr has this option (Projects -> Project Reports -> Project Runs).

**Comment by jbtronics** [comment]
The Part-DB rewrite offers a possibility to build parts and make them part of the inventory: https://github.com/Part-DB/Part-DB-server
