### ISSUE TITLE
Devices built - Parts stock update

### ISSUE THREAD

**Issue by jhs0** [Part-DB/Part-DB-legacy#67]
Hello,

What is the logic in Device that has a set of parts?
When I build a device, I increase the number.
Then I would expect the relevant parts to decrease stock quantity, because they were installed in that device, so no longer in stock.
Instead, they increase.

What have I taken the wrong way?

Thanks,
Ivan

**Comment by jbtronics** [comment]
Devices/Projects system was bigly overhauled for the Part-DB rewrite: https://github.com/Part-DB/Part-DB-server
