### ISSUE TITLE
Not able to Import More than 100 parts records using CSV Import

### ISSUE THREAD

**Issue by arivu95** [Part-DB/Part-DB-legacy#97]
I'm trying to Upload More than 500 records but not able to upload using a CSV file. Is there is any way to Increase the Limit for the import option? I'm also tried increasing the memory limit. If any steps is available please ping me or email me this id : arivu95@gmail.com.

Thanks and regards, 
N.Arivazhagan.
![test1](https://user-images.githubusercontent.com/61911965/114156201-f0fc7b80-993f-11eb-9836-adc1f0d32898.jpg)
![test2](https://user-images.githubusercontent.com/61911965/114156243-fbb71080-993f-11eb-951a-0cc7fdc1f135.jpg)

**Comment by jbtronics** [comment]
The import function of the Part-DB rewrite has no such limitation: https://github.com/Part-DB/Part-DB-server
